Upgrade RSpec 2.13.0 -> 2.14.3
This fixes an error in specs where the following was raised:

  Failure/Error: response.should redirect_to(root_path)
  NoMethodError: undefined method `assertions' for
  #<RSpec::Rails::TestUnitAssertionAdapter::AssertionDelegator:...>

Upgrading to the latest RSpec includes a fix for this issue.